/*
 * @Author: your name
 * @Date: 2019-11-28 14:49:55
 * @LastEditTime : 2020-01-28 12:17:36
 * @LastEditors  : Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: \reactNativeProject\myapp\root\redux\actiontypes.js
 */
export default {
    CHANGE_THEME:"CHANGE_THEME",
    POPULAR_REFRESH:"POPULAR_REFRESH",
    SHOW_THEME_VIEW:"SHOW_THEME_VIEW",
    LOAD_POPULAR_FALL:"LOAD_POPULAR_FALL",
    LOAD_POPULAR_SUCCESS:"LOAD_POPULAR_SUCCESS",
    POPULAR_LOAD_MORE_FALL:"LOAD_LOAD_MORE_FALL",
    POPULAR_LOAD_MORE_SUCCESS:"LOAD_LOAD_MORE_SUCCESS",
    FLUSH_POPULAR_FAVORITE:"FLUSH_POPULAR_FAVORITE",
    TRENDING_REFRESH:"TRENDING_REFRESH",
    TRENDING_REFRESH_FAIL:"TRENDING_REFRESH_FAIL",
    TRENDING_REFRESH_SUCCESS:"TRENDING_REFRESH_SUCCESS",
    TRENDING_LOAD_MORE_SUCCESS:"TRENDING_LOAD_MORE_SUCCESS",
    FLUSH_TRENDING_FAVORITE:"FLUSH_TRENDING_FAVORITE",
    TRENDING_LOAD_MORE_FAIL:"TRENDING_LOAD_MORE_FAIL",
    FAVORITE_LOAD_DATA:"FAVORITE_LOAD_DATA",
    FAVORITE_LOAD_SUCCESS:"FAVORITE_LOAD_SUCCESS",
    FAVORITE_LOAD_FAIL:"FAVORITE_LOAD_FAIL",
    LANGUAGE_LOAD_SUCCESS:"LANGUAGE_LOAD_SUCCESS"
}